import fs from 'fs'
import glob from 'glob'
import mkdirp from 'mkdirp'
import remapToFaker from './remapToFaker'

const config = {
  src: './specs',
  dest: './output'
}

const getSpecsFromFile = (file) => {
  const specs = fs.readFileSync(file, 'utf-8')
  if (!specs) return

  return JSON.parse(specs)
}

const writeSpecsToFile = (fileName, specs) => {
  const filePath = fileName.replace(config.src, config.dest)
  const specOutput = JSON.stringify(specs, null, 2)

  fs.writeFile(filePath, specOutput, err => {
    if (err) {
      console.error(error)
      return process.exit(1)
    } else {
      console.log(`${filePath} generated by Specter.`)
    }
  })
}

glob(`${config.src}/**/*`, {}, (err, files) => {
  mkdirp(config.dest)

  files.forEach(file => {
    const specs = remapToFaker(getSpecsFromFile(file))
    writeSpecsToFile(file, specs)
  })
})
